### PR TITLE
updated composer

### PR DESCRIPTION
**Pull request by microstudi**
Hi,
I've updated some composer dependencies (specially the guzzle component to version 6). Otherwise cannot be used in modern frameworks.
In case you want to merge it.

### CODE REVIEW

**Comment by ambroisemaupate** [comment]
Thanks for your PR. We are going to check it soon. But Guzzle 6 is now compatible with PHP 5.5 minimum, some of our libs are still compatible with PHP 5.4.

**Comment by microstudi** [comment]
As you wish, you always can use specific versions for old php installs.
I've tested the code with facebook and twitter and it works perfectly.

**Comment by patrickgalbraith** [comment]
Would be nice to get this merged. Running into this issue as well. Especially since PHP <5.6 is EOL (http://php.net/supported-versions.php)

**Comment by ambroisemaupate** [comment]
I’ll close this pull request as I changed composer.json allowing guzzle 5.* **or** 6.*

**Pull request closed without merging**
